version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

  app:
    build: .
    # Container name will be determined by the Jenkins pipeline
    # container_name: todo-app - removing this to allow dynamic naming
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - todo-network
    labels:
      project: "todo-app"
      # The color label will be added by Jenkins pipeline

volumes:
  mongo-data:

networks:
  todo-network:
    driver: bridge
